import streamlit as st
import requests
from PIL import Image
import io
import base64

# Function to convert image to base64
def image_to_base64(image):
    buffered = io.BytesIO()
    image.save(buffered, format="PNG")
    img_str = base64.b64encode(buffered.getvalue()).decode("utf-8")
    return img_str

# Function to make prediction
def predict_image(image_bytes, api_url="http://localhost:8000/predict"):
    files = {'file': ('image.jpg', image_bytes, 'image/jpeg')}
    try:
        response = requests.post(api_url, files=files, timeout=30)
        response.raise_for_status()
        return response.json()
    except requests.exceptions.RequestException as e:
        st.error(f"Error connecting to API: {e}")
        return None

def app():
    st.markdown('<h1 class="title-font">📸 Detection Page</h1>', unsafe_allow_html=True)

    st.header("🔍 AI vs Real Image Detection")
    st.markdown("""
                **🤖 Ready to detect AI-generated images?** 
            
                Upload an image for analysis. Our model will determine if it's a real photograph or AI-generated.
            """)
    with st.expander("See More Details"):
        st.markdown("""
                ### 📂 Upload an Image
                Select any image from your device for evaluation. Supported formats: **JPG, JPEG, PNG, BMP**.

                ### How It Works:
                - **Upload:** 
                Upload any image to analyze its authenticity. 📷

                - **Analyze:** 
                Our deep learning model and multiple heuristic techniques process the image to detect AI-generation patterns. 🔬

                - **Get Insights:** 
                Get immediate feedback with confidence scores and detailed explanations. 💡

                ### Analysis Techniques:
                1. **Deep Learning Model** - CNN trained to detect AI-generated patterns
                2. **Texture Analysis** - Local Binary Patterns for texture uniformity
                3. **Edge Analysis** - Edge density and blur pattern detection
                4. **Color Analysis** - Saturation and color distribution examination
                5. **Frequency Analysis** - FFT analysis for GAN artifacts

                Ready to upload? Let's detect AI images together! 🚀
                """)
    
    
    uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png", "bmp", "webp"])

    if uploaded_file is not None:
        image = Image.open(uploaded_file)
        image = image.resize((500, 500))
        img_base64 = image_to_base64(image)
        st.markdown(f"""
            <div style='text-align: center;'>
                <img src="data:image/png;base64,{img_base64}" width="500" style='border-radius: 15px; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);'/>
                <div style='margin-top: 10px; font-size: 16px; color: #666;'>🖼️ Uploaded Image</div>
            </div>
            """, unsafe_allow_html=True)

        # Make prediction
        with st.spinner('🔍 Analyzing image... Please wait.'):
            # Convert image to bytes
            img_byte_arr = io.BytesIO()
            image.save(img_byte_arr, format='PNG')
            img_byte_arr = img_byte_arr.getvalue()
            
            result = predict_image(img_byte_arr)

        if result is not None:
            classification = result['result']
            confidence = result['confidence'] * 100

            # Display main result
            if classification == 'real':
                st.markdown(f"""
                    <div class="real-result">
                        <h3 style='color: #00a000;'>✅ REAL IMAGE DETECTED</h3>
                        <p style='color: #0F0F0F;'>Detection: Real Photograph (Confidence: {confidence:.2f}%)</p>
                    </div>
                """, unsafe_allow_html=True)
                st.success("This appears to be a genuine photograph taken with a camera. 📷✨")
            else:
                st.markdown(f"""
                    <div class="fake-result">
                        <h3 style='color: #d00000;'>🚨 AI-GENERATED IMAGE DETECTED</h3>
                        <p style='color: #0F0F0F;'>Detection: AI-Generated (Confidence: {confidence:.2f}%)</p>
                    </div>
                """, unsafe_allow_html=True)
                st.error("This image appears to be artificially generated by AI. 🤖⚠️")

            # Display detailed scores
            detailed = result['detailed']
            st.markdown(f"""
                        <div class='dmain'>
                            <h3>📊 Detailed Analysis Scores</h3>
                            <p><strong>Texture Score:</strong> {detailed['texture_score']:.4f}</p>
                            <p><strong>Edge Anomaly Score:</strong> {detailed['edge_score']:.4f}</p>
                            <p><strong>Color Anomaly Score:</strong> {detailed['color_score']:.4f}</p>
                            <p><strong>FFT Anomaly Score:</strong> {detailed['fft_score']:.4f}</p>
                            <p><strong>Combined Heuristic Score:</strong> {detailed['combined_score']:.4f}</p>
                        </div>
                    """, unsafe_allow_html=True)

            # Display reasoning
            st.markdown('<div class="dmain">', unsafe_allow_html=True)
            st.markdown("### 🧠 Analysis Reasoning")
            for idx, reason in enumerate(result['reasons'], 1):
                st.markdown(f"""
                    <div class="reason-box">
                        <strong>{idx}.</strong> {reason}
                    </div>
                """, unsafe_allow_html=True)
            st.markdown('</div>', unsafe_allow_html=True)

            # Score interpretation
            with st.expander("ℹ️ Understanding the Scores"):
                st.markdown("""
                    ### Score Interpretation:
                    
                    **Texture Score (0-1)**  
                    Measures uniformity in texture patterns using Local Binary Patterns.  
                    Higher values suggest artificial repetitive textures.
                    
                    **Edge Score (0-1)**  
                    Analyzes edge density and blur inconsistencies.  
                    AI images often have unnatural edge transitions.
                    
                    **Color Score (0-1)**  
                    Examines color saturation distribution.  
                    Synthetic images may have over-smooth color gradients.
                    
                    **FFT Score (0-1)**  
                    Frequency domain analysis detecting GAN artifacts.  
                    Unusual high-frequency patterns indicate AI generation.
                    
                    **Combined Score (0-1)**  
                    Weighted combination of all heuristics.  
                    Values above 0.6 strongly suggest AI generation.
                """)