import streamlit as st
from PIL import Image, ImageDraw

def app():
    # Function to round the corners of the image
    def round_corners(image, radius=15):
        width, height = image.size
        rounded_mask = Image.new('L', (width, height), 0)
        draw = ImageDraw.Draw(rounded_mask)
        draw.rounded_rectangle((0, 0, width, height), radius=radius, fill=255)

        # Create a new image with transparency and paste the original image onto it
        rounded_image = Image.new('RGBA', (width, height))
        rounded_image.paste(image, (0, 0), rounded_mask)
        return rounded_image

    # Load the image
    image_path = 'images/ACAS.png'
    image = Image.open(image_path)
    new_width = 1200
    new_height = 500
    resized_image = image.resize((new_width, new_height))
    rounded_image = round_corners(resized_image, radius=15)
    st.image(rounded_image, width='stretch') # use_container_width=True instead use the width='stretch' parameter

    st.markdown("""
                <div class="main">
                    <h2>Welcome to AI vs Real Image Detector 🔍</h2>
                    <p>
                        This web app harnesses the power of AI to detect whether images are real photographs 
                        or artificially generated by AI systems. Using advanced deep learning models and 
                        sophisticated heuristic analysis, AI Image Detector analyzes images to provide 
                        reliable predictions with detailed explanations. In an era of deepfakes and AI-generated 
                        content, our goal is to make image authenticity verification accessible and easy to 
                        use for everyone.
                    </p>
                    <div class="feature-box">
                        <h2>✨ Key Features:</h2>
                        <ul>
                            <li>🎯 <strong>High Accuracy Detection</strong>: Advanced CNN model trained to distinguish real from AI-generated images.</li>
                            <li>🔬 <strong>Multi-Dimensional Analysis</strong>: Texture, edge, color, and frequency spectrum analysis.</li>
                            <li>📊 <strong>Detailed Explanations</strong>: Understand the reasoning behind every prediction.</li>
                            <li>⚡ <strong>Fast Results</strong>: Quick processing times for instant image verification.</li>
                            <li>🧠 <strong>Transparent AI</strong>: See individual scores from multiple analysis techniques.</li>
                        </ul>
                    </div>
                    <div class="feature-box">
                        <h2>🔬 How It Works:</h2>
                        <ul>
                            <li>📷 <strong>Upload Image</strong>: Select any image (JPG, PNG, BMP) from your device.</li>
                            <li>🧠 <strong>Deep Learning Analysis</strong>: Our CNN model evaluates learned patterns of AI generation.</li>
                            <li>🎨 <strong>Texture Analysis</strong>: Local Binary Patterns detect unnatural texture uniformity.</li>
                            <li>📐 <strong>Edge Detection</strong>: Analyzes edge density and blur patterns.</li>
                            <li>🌈 <strong>Color Analysis</strong>: Examines color distribution and saturation anomalies.</li>
                            <li>📊 <strong>Frequency Analysis</strong>: FFT detects unusual patterns from GANs.</li>
                            <li>✅ <strong>Get Results</strong>: Receive classification with confidence score and detailed reasoning.</li>
                        </ul>
                    </div>
                </div>
            """, unsafe_allow_html=True)